# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Optival Demo

on:
  push:
    branches: [ "master" ]

  schedule:
    - cron: '* 20 * * *'

jobs:
  bran-optival-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: get output value
        id: getimage
        run: |
           echo "::set-output name=response::$(python optivalDemo.py)"
      - name: check the value
        run: |
          echo ${${{ steps.getimage.outputs.response }}}
        shell: bash
      - name: Send to Slack
        if: always()
        uses: ravsamhq/notify-slack-action@v1
        with:
          status: ${{ job.status }} # required
          notification_title: '{workflow} has {status_message}'
          message_format: '{emoji} *Current date:* ${{ steps.getimage.outputs.response }}'
          footer: 'Linked to {workflow} test on GitHub action'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_CHANNEL }}